### ISSUE TITLE
needs ctrl+u and ctrl+d to jump a few lines up and down

### ISSUE THREAD

**Issue by cciollaro** [vgmoose/urwiddu#1]
like in vim

**Comment by vgmoose** [comment]
Currently PAGE-UP and DOWN do this, but the vim-like shortcuts would be nice.

**Comment by cciollaro** [comment]
which one of these is PAGE-UP and DOWN

![image](https://cloud.githubusercontent.com/assets/1570159/17646968/4981acec-61ac-11e6-81bd-f9200ad6f759.png)

**Comment by vgmoose** [comment]
FN + up/down

**Comment by cciollaro** [comment]
just checking in on the status of this high priority issue, I'm finding the maintainer gorgeous

**Comment by vgmoose** [comment]
thanks
